packages:
  - "packages/*"

patchedDependencies:
  ts-json-schema-generator@2.9.0: patches/ts-json-schema-generator.patch

onlyBuiltDependencies:
  - "@getgrit/cli"
  - "@swc/core"
  - "@vscode/vsce-sign"
  - esbuild
  - keytar
  - protobufjs
  - sharp
  - spawn-sync

updateConfig:
  ignoreDependencies:
    - "@types/vscode"
    - "@types/node"

fetchRetryFactor: 2
fetchRetryMintimeout: 1000
fetchTimeout: 30000
