unstable_features = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

reorder_imports = true
reorder_imported_names = true

remove_nested_generics = true

indent_style = "Block"
imports_layout = "HorizontalVertical"

max_width = 100
