name: Release
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"

      - name: Get version and pre-release
        id: version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          LATEST_VERSION=$(grep -E '^## [0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1 | sed 's/^## //')

          if [ -z "$LATEST_VERSION" ] || [ "$PACKAGE_VERSION" != "$LATEST_VERSION" ]; then
            echo "Version mismatch: package.json ($PACKAGE_VERSION) vs CHANGELOG.md ($LATEST_VERSION)"
            exit 1
          fi

          VERSION="$PACKAGE_VERSION"
          PATCH=$(echo "$VERSION" | awk -F. '{print $3}')
          if [ "$PATCH" = "0" ]; then
            PRE_RELEASE=false
          else
            PRE_RELEASE=true
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "pre_release=$PRE_RELEASE" >> $GITHUB_OUTPUT
          echo "Versions match: $VERSION"

      - name: Setup Node + PNPM
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '22'
          pnpm-version: '10'

      - name: Create version branch and tag
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          BRANCH_NAME="release/v${VERSION}"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

          git tag "v${VERSION}"
          git push origin "v${VERSION}"

      - name: Package extension
        run: pnpm package

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          CHANGELOG_CONTENT=$(awk "/^## $VERSION$/{flag=1; next} (/^## / || /^<details>/){flag=0} flag" CHANGELOG.md)

          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "Warning: No changelog content found for version $VERSION"
            CHANGELOG_CONTENT="- No changelog content available"
          fi

          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish to VS Code Marketplace
        run: |
          if [ "${{ steps.version.outputs.pre_release }}" = "true" ]; then
            pnpm run publish --pre-release
          else
            pnpm run publish
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: ./*.vsix
          prerelease: ${{ steps.version.outputs.pre_release }}
          generate_release_notes: false
          body: |
            🎉 New release v${{ steps.version.outputs.version }}

            ## What's Changed
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}

            ${{ steps.version.outputs.pre_release == 'true' && '⚠️ **This is a pre-release version.**' || '' }}

            ## Installation
            Download the `.vsix` file below and install it manually in VS Code, or install from the marketplace.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-${{ steps.version.outputs.version }}
          path: ./*.vsix
          if-no-files-found: error

      - name: Generate build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ./*.vsix

      - name: Close waiting-for-release issues
        if: success() && steps.version.outputs.pre_release != 'true'
        uses: ./.github/actions/close-waiting-issues
        env:
          VERSION: ${{ steps.version.outputs.version }}
